Add building via CI
cucumber-sp/yandex-music-linux pull request #18
Opened 2024-01-31 20:13 UTC by Maks1mS

2024-01-31 21:09 UTC, Maks1mS commented
Насчёт Nix не уверен, т.к. не работал с ним, но вроде должно всё работать

2024-02-01 14:59 UTC, cucumber-sp requested changes

2024-02-01 14:59 UTC, cucumber-sp commented on .github/workflows/build.sh
> +        ./build_deb.sh
лучше вызывать через sh <filename> т.к. не проставлен chmod файла, у меня лично при вызове напрямую из bash скриптов работает 50/50

2024-02-01 14:59 UTC, cucumber-sp commented on .github/workflows/build.sh
> +        pacman -S --noconfirm git sudo base-devel p7zip nodejs jq npm electron libpulse
нет необходимости устанавливать electron и libpulse

2024-02-01 14:59 UTC, cucumber-sp commented on .github/workflows/build.yml
> +        run: ./.github/workflows/build.sh
может тоже использовать sh <filename>?

2024-02-01 15:39 UTC, Maks1mS commented on .github/workflows/build.sh
> +        pacman -S --noconfirm git sudo base-devel p7zip nodejs jq npm electron libpulse
Без electron и libpulse:

![image](https://github.com/cucumber-sp/yandex-music-linux/assets/36362599/f5aebe78-63a1-46e2-bc79-159f4f27b755)

Тестил через [act](https://github.com/nektos/act).

2024-02-01 16:52 UTC, cucumber-sp commented on .github/workflows/build.sh
> +        pacman -S --noconfirm git sudo base-devel p7zip nodejs jq npm electron libpulse
понял

2024-02-01 16:53 UTC, merged

2024-02-01 16:59 UTC, cucumber-sp commented
@Maks1mS только сейчас увидел, при вызове build_deb нужно указывать `-a all` чтобы собирать под все архитектуры